### PR TITLE
Add second argument checking to prevent unexpected behavior.

### PR DESCRIPTION
**Pull request by hovosanoyan**

### CODE REVIEW

**Comment by RyanZim** [comment]
Generally, I'm against type-checking in JS, but in this case it might make sense, since passing `undefined` would lead to weird filenames. @jprichardson thoughts?

**Comment by jprichardson** [comment]
Looks good, Node does it, so we should too.

**Comment by RyanZim** [comment]
Will merge and release as soon as I can.

**Comment by RyanZim** [comment]
@hovosanoyan Thanks!

**Comment by RyanZim** [comment]
Released in 4.2.1

**Pull request merged**
